import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,makeTask,makeGoal,observeActivity,durationMinutes,deleteHistory,pruneHistory,proposePlan,acceptPlan,suggestTasks,searchMemory,updateSettings,validateEndpoint,taskOrder} from '../shared/core.mjs';

test('capture starts off; foreground samples never log before consent',()=>{const s=emptyState();observeActivity(s,{app:'Code',title:'secret'});assert.equal(s.sessions.length,0);assert.equal(s.settings.micEnabled,false);});
test('activity merges continuous samples, but excludes titles unless opted in',()=>{const s=emptyState();s.settings.activityEnabled=true;observeActivity(s,{app:'Code',title:'secret',idleSeconds:0},new Date('2026-09-08T10:00:00'));observeActivity(s,{app:'Code',title:'secret',idleSeconds:0},new Date('2026-09-08T10:00:03'));assert.equal(s.sessions.length,1);assert.equal(s.sessions[0].title,'');assert.equal(durationMinutes(s.sessions[0]),.05);});
test('excluded app interrupts sessions, including short transitions back to the same app',()=>{const s=emptyState();s.settings.activityEnabled=true;for(const [sec,app] of [[0,'Code'],[3,'1Password'],[6,'Code']])observeActivity(s,{app,title:'',idleSeconds:0},new Date(`2026-09-08T10:00:0${sec}`));assert.equal(s.sessions.length,2);assert.equal(s.sessions.reduce((n,x)=>n+durationMinutes(x),0),0);});
test('idle is distinct from productivity; locked periods and downtime are not counted',()=>{const s=emptyState();s.settings.activityEnabled=true;observeActivity(s,{app:'Chrome',idleSeconds:0},new Date('2026-09-08T10:00:00'));observeActivity(s,{app:'Chrome',idleSeconds:300},new Date('2026-09-08T10:00:03'));observeActivity(s,{app:'Chrome',locked:true},new Date('2026-09-08T10:00:06'));observeActivity(s,{app:'Chrome',idleSeconds:0},new Date('2026-09-08T11:00:00'));assert.equal(s.sessions.length,3);assert.equal(s.sessions[1].inputIdle,true);assert.equal(s.sessions[1].intent,'unknown');assert.equal(s.sessions.reduce((n,x)=>n+durationMinutes(x),0),0);});
test('midnight creates a new session and duration can be clipped to local day',()=>{const s=emptyState();s.settings.activityEnabled=true;observeActivity(s,{app:'Code'},new Date('2026-09-08T23:59:58'));observeActivity(s,{app:'Code'},new Date('2026-09-09T00:00:01'));assert.equal(s.sessions.length,2);assert.equal(durationMinutes({start:'2026-09-08T23:50:00',end:'2026-09-09T00:10:00'},'2026-09-09'),10);});
test('tasks preserve want/have distinction independent of deadline and validate dates',()=>{const t=makeTask({title:' Build a project ',commitment:'want_to',due:'2026-10-01',minutes:45});assert.equal(t.commitment,'want_to');assert.equal(t.due,'2026-10-01');assert.equal(t.title,'Build a project');assert.throws(()=>makeTask({title:'',due:''}));assert.throws(()=>makeTask({title:'x',due:'2026-02-31'}));assert.throws(()=>makeGoal({title:''}));});
test('planner ranks deadlines and respects existing blocks, budget, and day end',()=>{const s=emptyState();s.settings.dayEnd='12:00';s.tasks=[makeTask({title:'Later',minutes:60}),makeTask({title:'Exam',due:'2026-09-08',minutes:30})];s.blocks=[{id:'b',taskId:'external',start:'2026-09-08T10:00:00',end:'2026-09-08T10:30:00'}];const plan=proposePlan(s,new Date('2026-09-08T10:00:00'),60);assert.equal(plan.blocks.length,1);assert.equal(plan.blocks[0].title,'Exam');assert.equal(new Date(plan.blocks[0].start).getHours(),10);assert.equal(new Date(plan.blocks[0].start).getMinutes(),30);assert.equal(plan.unscheduled.length,1);assert.equal(s.blocks.length,1);});
test('accepting an overlapping plan fails atomically',()=>{const s=emptyState();const t=makeTask({title:'Study'});s.tasks=[t];const blocks=[{taskId:t.id,title:t.title,start:'2026-09-08T10:00:00',end:'2026-09-08T10:30:00'},{taskId:t.id,title:t.title,start:'2026-09-08T10:15:00',end:'2026-09-08T10:45:00'}];assert.throws(()=>acceptPlan(s,blocks),/overlap/);assert.equal(s.blocks.length,0);});
test('captured commitments go to inbox without inventing a deadline, and duplicates are suppressed',()=>{const s=emptyState();const m={id:'m',createdAt:'2026-09-08T10:00:00Z',text:'I have to review chapter four tomorrow. I want to build a project.'};suggestTasks(s,m);suggestTasks(s,m);assert.equal(s.tasks.length,2);assert.ok(s.tasks.every(t=>t.status==='inbox'&&t.sourceId==='m'&&t.due===''));assert.equal(s.tasks[1].commitment,'want_to');assert.equal(taskOrder(s.tasks).length,0);});
test('recent deletion clips sessions and cascades to inbox while retaining accepted tasks',()=>{const s=emptyState();s.sessions=[{id:'s',start:'2026-09-08T10:00:00Z',end:'2026-09-08T11:00:00Z'}];s.memories=[{id:'m',createdAt:'2026-09-08T10:50:00Z',text:'private memory',kind:'note'}];s.tasks=[makeTask({title:'Accepted',sourceId:'m'}),makeTask({title:'Pending',sourceId:'m',status:'inbox'})];deleteHistory(s,new Date('2026-09-08T10:45:00Z'));assert.equal(s.sessions[0].end,'2026-09-08T10:45:00.000Z');assert.equal(s.tasks.length,1);assert.equal(s.tasks[0].sourceId,'');assert.equal(searchMemory(s,'private').length,0);});
test('retention prunes old sources and does not leave stale source references',()=>{const s=emptyState();s.memories=[{id:'old',createdAt:'2026-01-01T00:00:00Z',text:'old'},{id:'new',createdAt:'2026-09-08T00:00:00Z',text:'new'}];s.tasks=[makeTask({title:'Keep',sourceId:'old'})];pruneHistory(s,new Date('2026-09-01T00:00:00Z'));assert.equal(s.memories.length,1);assert.equal(s.tasks[0].sourceId,'');});
test('provider validation restricts local transcription and rejects credential URLs or insecure remote AI',()=>{assert.equal(validateEndpoint('http://127.0.0.1:8080/inference',true),'http://127.0.0.1:8080/inference');assert.throws(()=>validateEndpoint('https://remote.example/inference',true));assert.throws(()=>validateEndpoint('http://remote.example'));assert.throws(()=>validateEndpoint('https://secret@example.com'));assert.throws(()=>updateSettings(emptyState().settings,{aiMode:'ollama',aiEndpoint:'https://remote.example'}));assert.throws(()=>updateSettings(emptyState().settings,{dayEnd:'25:00'}));});
