import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState} from '../shared/core.mjs';
import {observeJournal,closeJournal,journalEntries} from '../shared/journal.mjs';
function setup(){const s=emptyState();Object.assign(s.settings,{activityEnabled:true,titlesEnabled:true});return s;}
const base=+new Date('2026-09-08T10:00:00');
function feed(s,from,to,app='valorant-win64-shipping',extra={}){for(let sec=from;sec<=to;sec+=3)observeJournal(s,{app,title:'',idleSeconds:0,...extra},new Date(base+sec*1000));}
test('nothing is persisted until five minutes of foreground activity',()=>{const s=setup();feed(s,0,297);assert.equal(s.sessions.length,0);feed(s,300,300);assert.equal(s.sessions.length,1);assert.equal(s.sessions[0].label,'Valorant');assert.equal(s.sessions[0].activeSeconds,300);});
test('brief Discord and browser detours stay inside a dominant game block',()=>{const s=setup();feed(s,0,600);feed(s,603,630,'Discord');feed(s,633,660,'chrome');feed(s,663,1200);assert.equal(s.sessions.length,1);assert.equal(s.sessions[0].end,new Date(base+1200000).toISOString());assert.equal(s.sessions[0].activeSeconds,1140);});
test('sustained switch starts a separate block at the original switch time',()=>{const s=setup();feed(s,0,600);feed(s,603,1203,'chrome',{title:'A video - YouTube',idleSeconds:900});assert.equal(s.sessions.length,2);assert.equal(s.sessions[1].label,'YouTube');assert.equal(s.sessions[1].start,new Date(base+603000).toISOString());assert.equal(s.sessions[1].title,'A video - YouTube');assert.equal(s.sessions[1].purpose,undefined);});
test('short titles are not retained inside an otherwise sustained app',()=>{const s=setup();feed(s,0,60,'chrome',{title:'Brief video - YouTube'});feed(s,63,603,'chrome',{title:'Long video - YouTube'});assert.equal(s.sessions.length,1);assert.equal(s.sessions[0].title,'Long video - YouTube');assert.ok(!JSON.stringify(s.sessions).includes('Brief video'));});
test('pause, exclusion, lock, idle, downtime, and explicit close cannot bridge blocks',()=>{for(const reason of ['paused','excluded','locked','idle','gap','close']){const s=setup();feed(s,0,600);if(reason==='paused')s.settings.paused=true;if(reason==='close')closeJournal(s);if(reason!=='gap'&&reason!=='close')feed(s,603,603,reason==='excluded'?'1password':'Code',{locked:reason==='locked',idleSeconds:reason==='idle'?500:0});s.settings.paused=false;feed(s,630,1230);assert.equal(s.sessions.length,2,reason);}});
test('rapid repeated detours cannot turn a mostly different period into gaming',()=>{const s=setup();feed(s,0,300);for(let t=303;t<1800;t+=90){feed(s,t,t+72,'Discord');feed(s,t+75,t+87);}assert.ok(s.sessions.every(r=>r.activeSeconds/((new Date(r.end)-new Date(r.start))/1000)>=.7));});
test('midnight splits candidates and privacy opt-outs are respected',()=>{const s=setup();s.settings.titlesEnabled=false;feed(s,0,600,'Code',{title:'private'});assert.equal(s.sessions[0].title,'');s.settings.activityEnabled=false;feed(s,603,1203);assert.equal(s.sessions.length,1);const x=setup();for(let t=0;t<=600;t+=3)observeJournal(x,{app:'Code',idleSeconds:0},new Date(+new Date('2026-09-08T23:56:00')+t*1000));assert.equal(x.sessions.length,1);assert.equal(new Date(x.sessions[0].start).getDate(),9);});
test('legacy history stays intact while short entries are omitted',()=>{const rows=[{id:'short',app:'Code',start:new Date(base).toISOString(),end:new Date(base+3000).toISOString()},{id:'long',app:'Code',start:new Date(base).toISOString(),end:new Date(base+600000).toISOString()}];assert.equal(journalEntries(rows).length,1);assert.equal(rows.length,2);});
