import test from 'node:test';
import assert from 'node:assert/strict';
import {daySessions,observeSessionTotals} from '../shared/sessions.mjs';
import {emptyState,deleteHistory} from '../shared/core.mjs';
const start=+new Date('2026-09-08T17:00:00'),now=new Date('2026-09-09T12:00:00');
function row(minute,app,seconds=60){return {id:`${minute}:${app}`,minute:true,app,start:new Date(start+minute*60000).toISOString(),end:new Date(start+(minute+1)*60000).toISOString(),activeSeconds:seconds};}
test('two hours with 90 minutes of Valorant and 30 of browser detours is one session',()=>{const rows=[];for(let m=0;m<120;m++)rows.push(row(m,m%20<15?'valorant-win64-shipping':'chrome'));const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,1);assert.equal(s[0].winner.label,'Valorant');assert.equal(s[0].winner.seconds,5400);assert.equal(s[0].apps[1].seconds,1800);assert.equal(new Date(s[0].end)-new Date(s[0].start),7200000);});
test('YouTube binge followed by gaming creates two variable-length sessions',()=>{const rows=[];for(let m=0;m<90;m++)rows.push({...row(m,'chrome'),label:'YouTube',detail:'Video'});for(let m=90;m<210;m++)rows.push(row(m,(m-90)%20<15?'valorant-win64-shipping':'chrome'));const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,2);assert.equal(s[0].winner.label,'YouTube');assert.equal(s[1].winner.label,'Valorant');assert.equal(s[1].start,new Date(start+90*60000).toISOString());});
test('idle creates its own session and is never absorbed into gaming',()=>{const rows=[];for(let m=0;m<30;m++)rows.push(row(m,'valorant-win64-shipping'));for(let m=30;m<60;m++)rows.push({...row(m,'Discord'),label:'Idle',detail:'Idle',category:'idle'});for(let m=60;m<90;m++)rows.push(row(m,'valorant-win64-shipping'));assert.deepEqual(daySessions(rows,'2026-09-08',now).map(s=>s.winner.label),['Valorant','Idle','Valorant']);});
test('no-input game and Discord samples become Idle; passive YouTube stays separate',()=>{for(const app of ['valorant-win64-shipping','Discord','chrome']){const s=emptyState();Object.assign(s.settings,{activityEnabled:true,titlesEnabled:true});for(let sec=0;sec<=360;sec+=3)observeSessionTotals(s,{app,title:app==='chrome'?'Video - YouTube':'',idleSeconds:500},new Date(start+sec*1000));const sessions=daySessions(s.sessions,'2026-09-08',now);assert.equal(sessions[0].winner.label,app==='chrome'?'YouTube':'Idle');}});
test('same app after an unobserved gap is a distinct session',()=>{const rows=[];for(let m=0;m<15;m++)rows.push(row(m,'Code'));for(let m=30;m<45;m++)rows.push(row(m,'Code'));assert.equal(daySessions(rows,'2026-09-08',now).length,2);});
test('video titles aggregate inside details without becoming separate sessions',()=>{const rows=[];for(let m=0;m<30;m++)rows.push({...row(m,'chrome'),label:'YouTube',detail:'Video',titles:[{text:m<15?'First video':'Second video',seconds:60}]});const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,1);assert.equal(s[0].apps[0].titles.length,2);assert.equal(s[0].apps[0].titles[0].seconds,900);});
test('rapid switches accumulate app totals without storing switch order',()=>{const s=emptyState();s.settings.activityEnabled=true;for(let n=0;n<=60;n+=3)observeSessionTotals(s,{app:n%6?'Discord':'chrome',idleSeconds:0},new Date(start+n*1000));assert.equal(s.sessions.length,2);assert.ok(s.sessions.every(r=>r.activeSeconds===30));});
test('partial deletion scales minute totals and title time',()=>{const s=emptyState();s.sessions=[{...row(0,'chrome'),titles:[{text:'Video',seconds:60}]}];deleteHistory(s,new Date(start+30000));assert.equal(s.sessions[0].activeSeconds,30);assert.equal(s.sessions[0].titles[0].seconds,30);});
test('stale samples and exclusions do not become activity',()=>{const s=emptyState();s.settings.activityEnabled=true;observeSessionTotals(s,{app:'Code',idleSeconds:0},new Date(start));observeSessionTotals(s,{app:'Code',idleSeconds:0},new Date(start+30000));observeSessionTotals(s,{app:'1password',idleSeconds:0},new Date(start+33000));assert.equal(s.sessions.length,0);});
test('a final browser detour stays with gaming when YouTube starts next',()=>{const rows=[];for(let m=0;m<120;m++)rows.push(row(m,m%20<15?'valorant-win64-shipping':'chrome'));for(let m=120;m<180;m++)rows.push({...row(m,'chrome'),label:'YouTube',detail:'Video'});const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,2);assert.equal(s[0].apps[1].seconds,1800);assert.equal(s[0].end,new Date(start+120*60000).toISOString());assert.equal(s[1].start,s[0].end);});
test('a one-minute Discord check does not erase a sustained YouTube transition',()=>{const rows=[];for(let m=0;m<60;m++)rows.push(row(m,'valorant-win64-shipping'));for(let m=60;m<120;m++)rows.push(m%10===9?row(m,'Discord'):{...row(m,'chrome'),label:'YouTube',detail:'Video'});const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,2);assert.equal(s[1].winner.label,'YouTube');assert.equal(s[1].start,new Date(start+60*60000).toISOString());assert.equal(s[1].apps[1].seconds,360);});
test('brief returns to the previous game do not erase a mostly YouTube transition',()=>{const rows=[];for(let m=0;m<60;m++)rows.push(row(m,'valorant-win64-shipping'));for(let m=60;m<120;m++)rows.push(m%10===9?row(m,'valorant-win64-shipping'):{...row(m,'chrome'),label:'YouTube',detail:'Video'});const s=daySessions(rows,'2026-09-08',now);assert.equal(s.length,2);assert.equal(s[1].winner.label,'YouTube');assert.equal(s[1].start,new Date(start+60*60000).toISOString());});
