import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowUp,ArrowRight,AudioLines,BookOpen,Check,CheckCheck,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Code2,Coffee,Command,Download,Flag,Focus,History,LayoutDashboard,ListTodo,LoaderCircle,LockKeyhole,Mic,Monitor,MoreHorizontal,Pause,Play,Plus,Search,Settings2,ShieldCheck,Sparkles,Sun,Target,Trash2,Volume2,X} from 'lucide-react';
import {createPreview} from './preview';
import {useAudioCapture} from './audio';
import {durationMinutes,localDate,taskOrder} from '../shared/core.mjs';
import './styles.css';
import './minimal.css';
import ActivityOverview from './ActivityOverview';

const api=window.argus || createPreview();
const preview=api.platform==='preview';
const nav=[['Today',LayoutDashboard],['Timeline',History],['Tasks',ListTodo],['Goals',Target],['Memory',BookOpen]];
const time=value=>new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});
const minutes=value=>{const n=Math.round(value);return n>=60?`${Math.floor(n/60)}h ${n%60}m`:`${n}m`;};
const dateLabel=value=>value ? new Date(`${value}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric'}) : 'No deadline';
function IconButton({label,children,...props}){return <button className="icon-button" title={label} aria-label={label} {...props}>{children}</button>;}
function Empty({icon:Icon=Sparkles,title,children,action}){return <div className="empty"><span className="empty-icon"><Icon size={25}/></span><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Modal({title,children,onClose}){
  const ref=useRef();useEffect(()=>{const previous=document.activeElement;ref.current?.focus();function key(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=ref.current.querySelectorAll('button,input,select,textarea,[tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={ref} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-heading"><h2>{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={20}/></IconButton></div>{children}</section></div>;
}
function App(){
  const [state,setState]=useState(null),[page,setPage]=useState('Today'),[modal,setModal]=useState(null),[toast,setToast]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[chat,setChat]=useState([]),[thinking,setThinking]=useState(false),[draft,setDraft]=useState(''),[selectedDate,setSelectedDate]=useState(localDate()),[filter,setFilter]=useState('All tasks'),[goalFilter,setGoalFilter]=useState(''),[plan,setPlan]=useState(null),[source,setSource]=useState(null),[tick,setTick]=useState(Date.now());
  const chatEnd=useRef();const previousMemoryIds=useRef(null);
  useEffect(()=>{api.invoke('snapshot').then(setState).catch(e=>setToast({text:e.message,error:true}));return api.subscribe(setState);},[]);
  useEffect(()=>{const id=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id);},[]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(null),5500);return()=>clearTimeout(id);}},[toast]);
  useEffect(()=>{chatEnd.current?.scrollIntoView({block:'nearest'});},[chat,thinking]);
  useEffect(()=>{if(!state)return;const ids=new Set(state.memories.map(m=>m.id));if(previousMemoryIds.current&&[...previousMemoryIds.current].some(id=>!ids.has(id)))setChat([]);previousMemoryIds.current=ids;},[state]);
  useAudioCapture(api,state);
  async function act(action,payload,success){try{const result=await api.invoke(action,payload);setState(await api.invoke('snapshot'));if(success)setToast({text:success});return result;}catch(e){setToast({text:e.message,error:true});throw e;}}
  const safe=(action,payload,success)=>act(action,payload,success).catch(()=>{});
  async function submitTask(e){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));try{const task=await act('task:add',data);setModal(null);setToast({text:'Task added. A little more clarity.',undo:()=>safe('task:delete',{id:task.id})});}catch{}finally{setBusy(false);}}
  async function submitGoal(e){e.preventDefault();setBusy(true);try{await act('goal:add',Object.fromEntries(new FormData(e.currentTarget)),'Your goal has a home.');setModal(null);}catch{}finally{setBusy(false);}}
  async function ask(text=draft){if(!text.trim()||thinking)return;setDraft('');setChat(c=>[...c,{role:'user',text}]);setThinking(true);try{const match=text.match(/^(?:add (?:a )?task[:\s]+|remind me to\s+|i (?:have|need|want) to\s+)(.+)$/i);if(match){const task=await act('task:add',{title:match[1],commitment:/i want to/i.test(text)?'want_to':'have_to'});setChat(c=>[...c,{role:'assistant',text:`Added “${task.title}” to ${task.commitment==='have_to'?'Have to do':'Want to do'}. You can set its deadline in Tasks.`,taskId:task.id}]);}else{const result=await api.invoke('chat',{question:text});setChat(c=>[...c,{role:'assistant',...result}]);}}catch(e){setChat(c=>[...c,{role:'assistant',text:e.message,error:true}]);}finally{setThinking(false);}}
  async function buildPlan(){setBusy(true);try{setPlan(await api.invoke('plan:propose'));setModal('plan');}catch(e){setToast({text:e.message,error:true});}finally{setBusy(false);}}
  if(!state)return <main className="loading"><div className="brand-mark">a</div><p>{toast?.text||'Making space for your day…'}</p></main>;
  const today=localDate();const priorities=taskOrder(state.tasks);const todaySessions=state.sessions.filter(s=>durationMinutes(s,today)>0);
  const total=todaySessions.reduce((a,s)=>a+durationMinutes(s,today),0),aligned=todaySessions.filter(s=>s.intent==='goal-aligned').reduce((a,s)=>a+durationMinutes(s,today),0);
  const completed=state.tasks.filter(t=>t.status==='done'&&t.completedAt&&localDate(new Date(t.completedAt))===today).length;
  const inbox=state.tasks.filter(t=>t.status==='inbox');const allActive=state.settings.activityEnabled||state.settings.screenEnabled||state.settings.micEnabled||state.settings.playbackEnabled;
  const activeCapture=state.runtime.health?.state==='active';
  const focusRemaining=state.focus?Math.max(0,Math.ceil((new Date(state.focus.end)-tick)/1000)):0;
  const selectedSource=source&&(state.memories.find(m=>m.id===source)||state.sessions.find(s=>s.id===source));
  const sessionRows=state.sessions.filter(s=>localDate(new Date(s.start))===selectedDate).slice().reverse();
  const foundMemories=state.memories.filter(m=>!query||`${m.text} ${m.label}`.toLowerCase().includes(query.toLowerCase())).slice().reverse();
  const filteredTasks=state.tasks.filter(t=>(filter==='All tasks'?t.status!=='inbox':filter==='Have to do'?t.commitment==='have_to'&&t.status!=='inbox':filter==='Want to do'?t.commitment==='want_to'&&t.status!=='inbox':filter==='Inbox'?t.status==='inbox':t.status==='done')&&(!goalFilter||t.goalId===goalFilter)).sort((a,b)=>(a.status==='done')-(b.status==='done'));
  function taskRow(task,compact=false){const goal=state.goals.find(g=>g.id===task.goalId);return <div className={`task-row ${task.status==='done'?'is-done':''}`} key={task.id}><button className={`task-check ${task.status==='done'?'checked':''}`} aria-label={`${task.status==='done'?'Reopen':'Complete'} ${task.title}`} onClick={()=>safe('task:update',{id:task.id,status:task.status==='done'?'todo':'done'})}>{task.status==='done'&&<Check size={13}/>}</button><div className="task-copy"><button className="text-button task-title" onClick={()=>setModal({type:'editTask',task})}>{task.title}</button><div className="task-meta">{goal&&<span className={`goal-dot ${goal.color}`}>{goal.title}</span>}<span><Clock3 size={11}/>{task.minutes} min</span>{!compact&&task.due&&<span className={task.due<=today?'due-soon':''}><Flag size={11}/>{dateLabel(task.due)}</span>}</div></div><span className={`tag ${task.commitment==='have_to'?'tag-sage':'tag-neutral'}`}>{task.commitment==='have_to'?'Have to':'Want to'}</span>{task.status!=='done'&&<IconButton label={`Focus on ${task.title}`} onClick={()=>safe('focus:start',{taskId:task.id},'Focus session started.')}><Play size={15}/></IconButton>}{!compact&&<IconButton label={`Delete ${task.title}`} onClick={()=>setModal({type:'deleteTask',task})}><Trash2 size={15}/></IconButton>}</div>;}
  const goalCard=goal=>{const tasks=state.tasks.filter(t=>t.goalId===goal.id&&t.status!=='inbox'),done=tasks.filter(t=>t.status==='done').length,percent=tasks.length?Math.round(done/tasks.length*100):0;return <button className={`goal-card ${goal.color}`} key={goal.id} onClick={()=>{setGoalFilter(goal.id);setFilter('All tasks');setPage('Tasks');}}><div className="goal-card-top"><span className="goal-icon">{goal.color==='peach'?<BookOpen size={19}/>:<Code2 size={19}/>}</span><ArrowUpRight size={17}/></div><h3>{goal.title}</h3><p>{goal.target||goal.why||'Small steps, a meaningful direction.'}</p><div className="goal-progress"><span style={{width:`${percent}%`}}/></div><div className="goal-card-bottom"><span>{done} of {tasks.length} tasks complete</span><b>{percent}%</b></div></button>;};
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Today');}}><span className="brand-mark">a<span/></span><span>argus<span className="brand-period">.</span></span></a><div className="workspace-label">YOUR PERSONAL SPACE</div><nav aria-label="Main navigation">{nav.map(([name,Icon])=><button key={name} className={`nav-item ${page===name?'active':''}`} onClick={()=>{setPage(name);if(name==='Tasks')setGoalFilter('');}}><Icon size={19}/><span>{name}</span>{name==='Tasks'&&inbox.length>0&&<span className="nav-count">{inbox.length}</span>}{page===name&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-note"><span className="little-orbit">✳</span><p>A little intention.<br/>A meaningful day.</p><span>One step at a time.</span></div><div className="sidebar-bottom"><button className={`nav-item ${page==='Settings'?'active':''}`} onClick={()=>setPage('Settings')}><Settings2 size={19}/>Settings</button><div className="privacy-foot"><ShieldCheck size={15}/><span>{preview?'Preview workspace':'Your data stays with you'}</span></div><div className="profile"><span className="avatar">Y</span><div><b>Your workspace</b><span>{preview?'Sample day · browser preview':'Personal · stored locally'}</span></div><span className="profile-dot"/></div></div></aside>
  <div className="workspace"><header className="topbar"><div className="breadcrumb">Argus <ChevronRight size={13}/><b>{page}</b></div><div className="topbar-actions"><button className="search-shortcut" onClick={()=>setPage('Memory')}><Search size={15}/><span>Search</span></button><span className="top-divider"/><button className={`capture-pill ${activeCapture?'recording':''}`} onClick={()=>setPage('Settings')}><span/>{preview?'Preview':state.runtime.health?.label||'Tracking off'}</button><IconButton label="Add a task" onClick={()=>setModal('task')}><Plus size={19}/></IconButton></div></header>
  {preview&&<div className="preview-banner"><Monitor size={13}/> Interactive preview · this is a sample day. Real capture runs in the Windows app.</div>}
  <div className="content-layout"><main className="main-content">
  {page==='Today'&&<><div className="page-eyebrow">{new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</div><div className="page-heading"><h1>Today</h1><button className="button" onClick={()=>setModal('task')}>New task</button></div>
  <ActivityOverview state={state} preview={preview} onAction={safe} onSettings={()=>setPage('Settings')} onTimeline={()=>setPage('Timeline')}/>
  {!state.settings.onboarded&&!preview&&<section className="welcome-card"><div><h2>Set up Argus</h2><p>Choose what to track and add your first goal.</p></div><button className="button" onClick={()=>{safe('settings:update',{onboarded:true});setPage('Settings');}}>Settings</button></section>}
  <section className="day-plan-row"><div><h2>Plan your day</h2><p>{priorities.length} open tasks · {priorities.filter(t=>t.due&&t.due<=today).length} due by today</p></div><button className="button primary" disabled={busy} onClick={priorities.length?buildPlan:()=>setModal('task')}>{busy?'Preparing…':priorities.length?'Plan my day':'Add task'}</button></section>
  {state.focus&&<section className="focus-banner"><span className="focus-pulse"/><div><span className="eyebrow">{focusRemaining?'ONE THING AT A TIME':'YOUR FOCUS BLOCK IS COMPLETE'}</span><b>{state.focus.title}</b></div><strong>{Math.floor(focusRemaining/60).toString().padStart(2,'0')}:{(focusRemaining%60).toString().padStart(2,'0')}</strong><button className="button small" onClick={()=>safe('focus:stop',{})}>End session</button></section>}
  <section className="section"><div className="section-heading"><div><h2>Your next steps <span className="count-pill">{priorities.length}</span></h2><p>A clear place to put your energy.</p></div><button className="text-link" onClick={()=>{setPage('Tasks');setGoalFilter('');}}>All tasks <ArrowUpRight size={14}/></button></div><div className="task-list">{priorities.length?priorities.slice(0,3).map(t=>taskRow(t,true)):<Empty icon={ListTodo} title="A little clarity goes a long way">Add something you have to do, or something you want to make time for.</Empty>}<button className="add-task-row" onClick={()=>setModal('task')}><Plus size={16}/>Add a task<span>Get it out of your head, into your day.</span></button></div></section>
  <section className="section"><div className="section-heading"><div><h2>The bigger picture</h2><p>Small actions, connected to your ambitions.</p></div><button className="text-link" onClick={()=>setPage('Goals')}>Your goals <ArrowUpRight size={14}/></button></div><div className="goals-grid">{state.goals.slice(0,2).map(goalCard)}{state.goals.length===0&&<button className="new-goal-card" onClick={()=>setModal('goal')}><Target size={27}/><h3>What are you working toward?</h3><span>Give your next steps a direction <Plus size={15}/></span></button>}</div></section>
  <section className="section"><div className="section-heading"><h2>A glimpse of your day</h2><button className="text-link" onClick={()=>setPage('Timeline')}>Full timeline <ArrowUpRight size={14}/></button></div><div className="day-strip">{todaySessions.length?<><div className="activity-strip">{todaySessions.map(s=><button key={s.id} className={`strip-segment ${s.category}`} style={{flex:Math.max(1,durationMinutes(s))}} title={`${s.app} · ${minutes(durationMinutes(s))}`} onClick={()=>{setSource(s.id);setModal('source');}}/>)}</div><div className="strip-labels"><span>{time(todaySessions[0].start)}</span><span className="legend"><i/> Coding <i/> Learning <i/> Other</span><span>{time(todaySessions.at(-1).end)}</span></div></>:<p className="muted">Your activity will appear here after you enable app tracking.</p>}</div></section>
  </>}
  {page==='Tasks'&&<><PageTitle eyebrow="A LITTLE LESS MENTAL CLUTTER" title="A place for every next step." description="Keep your commitments. Make space for your curiosities." action={<button className="button primary" onClick={()=>setModal('task')}><Plus size={16}/>New task</button>}/><div className="toolbar"><div className="tabs">{['All tasks','Have to do','Want to do','Inbox','Done'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}{f==='Inbox'&&inbox.length>0&&<span>{inbox.length}</span>}</button>)}</div><select aria-label="Filter by goal" value={goalFilter} onChange={e=>setGoalFilter(e.target.value)}><option value="">All goals</option>{state.goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></div>{filter==='Inbox'&&<div className="info-note"><Sparkles size={16}/><p>Possible commitments from your memories. Check who said it, what they meant, and the deadline before accepting.</p></div>}<div className="task-list">{filteredTasks.length?filteredTasks.map(t=>filter==='Inbox'?<div className="inbox-row" key={t.id}><div><h3>{t.title}</h3><p>{t.details}</p><button className="text-link" onClick={()=>{setSource(t.sourceId);setModal('source');}}>View source <ArrowUpRight size={13}/></button></div><div className="row-actions"><button className="button small" onClick={()=>safe('task:delete',{id:t.id},'Suggestion dismissed.')}>Dismiss</button><button className="button primary small" onClick={()=>setModal({type:'acceptTask',task:t})}>Review & add</button></div></div>:taskRow(t)):<Empty icon={ListTodo} title={filter==='Inbox'?'Nothing waiting for review':'A little breathing room'}>{filter==='Inbox'?'Possible tasks from notes, screen text, and transcripts will appear here.':'No tasks match this view. Add a next step when you’re ready.'}</Empty>}</div></>}
  {page==='Goals'&&<><PageTitle eyebrow="YOUR NORTH STARS" title="Give your days a direction." description="Choose what matters. Progress is built one action at a time." action={<button className="button primary" onClick={()=>setModal('goal')}><Plus size={16}/>New goal</button>}/><div className="goals-grid full">{state.goals.map(g=><div key={g.id}>{goalCard(g)}<div className="goal-actions"><span>{g.due?`Target ${dateLabel(g.due)}`:'Your own pace'}</span><button className="text-link" onClick={()=>setModal({type:'deleteGoal',goal:g})}>Remove goal</button></div></div>)}<button className="new-goal-card" onClick={()=>setModal('goal')}><Plus size={28}/><h3>Something you want to become?</h3><span>Add a goal that feels like you.</span></button></div><div className="quote-card"><span>✳</span><p>You don’t have to change everything today.<br/>Just take a step in a direction you care about.</p></div></>}
  {page==='Timeline'&&<><PageTitle eyebrow="YOUR DAY, REMEMBERED" title="See where your day went." description="A local record of your activity. You decide what it means."/><div className="toolbar"><div className="date-control"><IconButton label="Previous day" onClick={()=>{const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()-1);setSelectedDate(localDate(d));}}><ChevronLeft size={16}/></IconButton><input aria-label="Timeline date" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/><IconButton label="Next day" onClick={()=>{const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()+1);setSelectedDate(localDate(d));}}><ChevronRight size={16}/></IconButton></div><span className="muted">{minutes(sessionRows.reduce((n,s)=>n+durationMinutes(s),0))} captured · {sessionRows.length} sessions</span></div><div className="info-note"><ShieldCheck size={16}/><p>App names are clues, not judgments. Correct a category or mark how a session related to your intentions.</p></div><div className="timeline-list">{sessionRows.length?sessionRows.map(s=><article className="timeline-row" key={s.id}><div className="timeline-time">{time(s.start)}<span>{time(s.end)}</span></div><div className={`app-icon ${s.category}`}>{s.category==='coding'?<Code2 size={20}/>:s.category==='studying'?<BookOpen size={20}/>:<Monitor size={20}/>}</div><div className="timeline-copy"><h3>{s.app}<span>{minutes(durationMinutes(s))}</span></h3><p>{s.title||'Window titles are not captured'}</p>{s.inputIdle&&<span className="idle-note"><Coffee size={12}/>No recent input · may still be watching or reading</span>}<div className="timeline-tags"><select aria-label={`Category for ${s.app} at ${time(s.start)}`} value={s.category} onChange={e=>safe('session:update',{id:s.id,category:e.target.value})}>{['coding','studying','communication','entertainment','other','unknown'].map(v=><option key={v}>{v}</option>)}</select><select aria-label={`Intent for ${s.app} at ${time(s.start)}`} value={s.intent} onChange={e=>safe('session:update',{id:s.id,intent:e.target.value})}>{['goal-aligned','planned leisure','possible distraction','unknown'].map(v=><option key={v}>{v}</option>)}</select></div></div></article>):<Empty icon={History} title="This day is still a blank page">No activity was captured for this date. Capture gaps and time away are never counted as work.</Empty>}</div></>}
  {page==='Memory'&&<><PageTitle eyebrow="LESS REMEMBERING. MORE LIVING." title="Your context, close at hand." description="Find a thought, a conversation, or something you were reading." action={<button className="button primary" onClick={()=>setModal('note')}><Plus size={16}/>Add a note</button>}/><div className="memory-search"><Search size={19}/><input aria-label="Search memories" placeholder="Search your memories…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<IconButton label="Clear search" onClick={()=>setQuery('')}><X size={16}/></IconButton>}</div><div className="memory-subheading"><span>{foundMemories.length} {foundMemories.length===1?'memory':'memories'}</span><span><LockKeyhole size={12}/>Stored in your workspace</span></div><div className="memory-grid">{foundMemories.length?foundMemories.map(m=><article className="memory-card" key={m.id}><div className="memory-card-top"><span>{m.kind==='audio'?<AudioLines size={16}/>:m.kind==='screen'?<Monitor size={16}/>:<BookOpen size={16}/>} {m.kind==='audio'?'Conversation':m.kind==='screen'?'Screen context':'Your note'}</span><IconButton label="Delete memory" onClick={()=>setModal({type:'deleteMemory',memory:m})}><Trash2 size={14}/></IconButton></div><button className="memory-body" onClick={()=>{setSource(m.id);setModal('source');}}>{m.text}</button><div className="memory-footer"><span>{new Date(m.createdAt).toLocaleDateString([],{month:'short',day:'numeric'})} · {time(m.createdAt)}</span><span>{m.label||'Personal'}</span></div></article>):<Empty icon={BookOpen} title="Make space for a thought">Add a note or enable optional capture. Your memories stay searchable for the retention period you choose.</Empty>}</div></>}
  {page==='Settings'&&<Settings state={state} act={act} setModal={setModal}/>}
  <footer className="page-footer"><span className="footer-mark">✳</span>A little more present. A little more intentional.<span>ARGUS · {preview?'PREVIEW':'LOCAL FIRST'}</span></footer>
  </main><aside className="assistant-panel"><div className="assistant-heading"><span className="assistant-icon"><Sparkles size={18}/></span><div><h2>Assistant</h2><span>{preview?'Preview companion':state.settings.aiMode==='offline'?'Offline planner & search':state.settings.aiMode==='ollama'?'Local AI companion':'Cloud AI · opt-in enabled'}</span></div></div><div className="assistant-scroll"><div className="assistant-welcome"><div className="tiny-star">✳</div><h3>Your day has context.<br/>Let’s put it to good use.</h3><p>Find what you need, untangle a thought, or work out your next step.</p></div><div className="prompt-chips">{['What should I focus on next?','Where did my time go today?','What did I say I needed to do?'].map(q=><button key={q} onClick={()=>ask(q)} disabled={thinking}>{q}<ArrowUpRight size={14}/></button>)}</div><div className="chat-messages" aria-live="polite">{chat.map((m,i)=><div key={i} className={`chat-message ${m.role} ${m.error?'error':''}`}>{m.role==='assistant'&&<span className="chat-label"><Sparkles size={12}/> ARGUS</span>}<p>{m.text}</p>{m.taskId&&<button className="text-link" onClick={()=>{safe('task:delete',{id:m.taskId},'Task removed.');setChat(c=>c.map((x,j)=>j===i?{...x,text:'Task creation undone.',taskId:null}:x));}}>Undo task creation</button>}{m.sources?.length>0&&<div className="source-links">{m.sources.map((s,j)=><button key={s.id} onClick={()=>{setSource(s.id);setModal('source');}}>[{j+1}] {s.kind} · {time(s.at)}<ArrowUpRight size={11}/></button>)}</div>}</div>)}{thinking&&<div className="thinking"><LoaderCircle size={14} className="spin"/>Finding a little clarity…</div>}<div ref={chatEnd}/></div>{!chat.length&&<div className="context-note"><div><span className="status-dot"/> YOUR CONTEXT</div><p>{state.memories.length} memories · {state.tasks.filter(t=>t.status==='todo').length} open tasks<br/>{state.goals.length} goals to work toward</p><span>Answers reference the context available.<br/>Missing history stays missing.</span></div>}</div><div className="assistant-bottom"><form onSubmit={e=>{e.preventDefault();ask();}}><textarea aria-label="Ask Argus" placeholder="Ask, remember, or think out loud…" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}}} rows={2}/><div className="composer-bottom"><span><LockKeyhole size={11}/>{state.settings.aiMode==='cloud'?'Selected context sent to provider':'Your space. Your context.'}</span><button className="send-button" aria-label="Send message" disabled={!draft.trim()||thinking}><ArrowUp size={17}/></button></div></form><p>Small steps look good on you.</p></div></aside></div></div>
  {modal==='task'&&<Modal title="A new next step" onClose={()=>setModal(null)}><form onSubmit={submitTask}><label>What’s on your mind?<input name="title" placeholder="e.g. Practice arrays for 30 minutes" required maxLength={240} autoFocus/></label><div className="form-grid"><label>Make space for<select name="commitment"><option value="have_to">Have to do</option><option value="want_to">Want to do</option></select></label><label>Estimated minutes<input name="minutes" type="number" min="5" max="480" defaultValue="30" required/></label><label>Deadline<input name="due" type="date"/></label><label>Priority<select name="priority" defaultValue="2"><option value="1">High</option><option value="2">Normal</option><option value="3">Low</option></select></label></div><label>Connected goal<select name="goalId" defaultValue={goalFilter}><option value="">No goal — just part of life</option>{state.goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>A little context<textarea name="details" placeholder="Anything your future self should know" rows={3}/></label><div className="modal-footer"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button primary" disabled={busy}>Add task <Plus size={15}/></button></div></form></Modal>}
  {modal==='goal'&&<Modal title="Give your days a direction" onClose={()=>setModal(null)}><form onSubmit={submitGoal}><label>What are you working toward?<input name="title" placeholder="Become a confident software developer" required maxLength={140} autoFocus/></label><label>Why does this matter to you?<textarea name="why" placeholder="Your reason, in your own words" rows={2}/></label><label>What would progress look like?<input name="target" placeholder="Ship a project I’m proud of"/></label><div className="form-grid"><label>Target date (optional)<input name="due" type="date"/></label><label>Color<select name="color"><option value="sage">Sage</option><option value="peach">Peach</option><option value="lavender">Lavender</option></select></label></div><div className="modal-footer"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button primary" disabled={busy}>Create goal <ArrowRight size={15}/></button></div></form></Modal>}
  {(modal?.type==='editTask'||modal?.type==='acceptTask')&&<Modal title={modal.type==='acceptTask'?'Review this commitment':'Edit your next step'} onClose={()=>setModal(null)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{await act('task:update',{id:modal.task.id,...data,...(modal.type==='acceptTask'?{status:'todo'}:{})},'Task updated.');setModal(null);}catch{}}}><label>Task<input name="title" defaultValue={modal.task.title} required maxLength={240}/></label><label>Deadline (leave empty if unknown)<input name="due" type="date" defaultValue={modal.task.due}/></label><p className="form-help">{modal.task.details||'A specific action is easier to start.'}</p><div className="modal-footer"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button primary">{modal.type==='acceptTask'?'Accept task':'Save changes'}</button></div></form></Modal>}
  {modal==='note'&&<Modal title="Keep a thought" onClose={()=>setModal(null)}><form onSubmit={async e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('text');try{await act('memory:add',{text},'Note saved locally.');setModal(null);}catch{}}}><label>Your note<textarea name="text" required rows={7} placeholder="Something to remember, an idea, a promise to yourself…" maxLength={30000} autoFocus/></label><p className="form-help">Possible commitments will appear in your task inbox for review.</p><div className="modal-footer"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button primary">Save note</button></div></form></Modal>}
  {modal==='plan'&&plan&&<Modal title="A little structure for your day" onClose={()=>setModal(null)}><p className="form-help">{plan.message}</p><div className="proposed-plan">{plan.blocks.map(b=><div key={b.id}><span>{time(b.start)}<small>{time(b.end)}</small></span><div><b>{b.title}</b><p>{b.reason}</p></div></div>)}</div><p className="form-help">Planning window ends at {state.settings.dayEnd}. Change your available time in Settings.</p><div className="modal-footer"><button className="button" onClick={()=>setModal(null)}>Keep thinking</button><button className="button primary" disabled={!plan.blocks.length} onClick={async()=>{try{await act('plan:accept',{blocks:plan.blocks},'Your plan is ready. One block at a time.');setModal('schedule');}catch{}}}>Use this plan <Check size={15}/></button></div></Modal>}
  {modal==='schedule'&&<Modal title="Your focus blocks" onClose={()=>setModal(null)}>{state.blocks.length?<div className="proposed-plan">{state.blocks.slice().sort((a,b)=>a.start.localeCompare(b.start)).map(b=><div key={b.id}><span>{time(b.start)}<small>{time(b.end)}</small></span><div><b>{b.title}</b><p>{new Date(b.start).toLocaleDateString()} · {b.reason}</p></div><IconButton label={`Remove block ${b.title}`} onClick={()=>safe('block:delete',{id:b.id})}><Trash2 size={15}/></IconButton></div>)}</div>:<Empty icon={Clock3} title="Room for a plan">Use Plan my day to propose focus blocks.</Empty>}</Modal>}
  {modal==='source'&&<Modal title="The original context" onClose={()=>setModal(null)}>{selectedSource?<><div className="source-meta">{new Date(selectedSource.createdAt||selectedSource.start).toLocaleString()} · {selectedSource.kind||selectedSource.app}</div><p className="source-text">{selectedSource.text||selectedSource.title||'Window title was not captured.'}</p>{selectedSource.app&&<p className="form-help">{selectedSource.category} · {selectedSource.intent} · {minutes(durationMinutes(selectedSource))}</p>}</>:<p className="form-help">This source is no longer available. It may have been deleted or expired.</p>}</Modal>}
  {(modal?.type?.startsWith('delete')||modal==='deleteAll'||modal==='deleteRecent')&&<Modal title="Remove this from your workspace?" onClose={()=>setModal(null)}><p className="form-help">{modal==='deleteAll'?'This removes all captured activity and memories, including pending task suggestions. Your accepted tasks and goals remain.':modal==='deleteRecent'?'This removes activity and memories from the last 15 minutes, including related pending task suggestions.':modal.type==='deleteGoal'?'The goal will be removed. Its tasks will remain without a linked goal.':modal.type==='deleteMemory'?'This memory and related inbox suggestions will be removed. Accepted tasks remain without their source link.':'This task and its scheduled blocks will be removed.'} This action cannot be undone.</p><div className="modal-footer"><button className="button" onClick={()=>setModal(null)}>Keep it</button><button className="button danger" onClick={async()=>{try{if(modal==='deleteAll'||modal==='deleteRecent'){await act('history:delete',{range:modal==='deleteAll'?'all':'recent'});setChat([]);}else if(modal.type==='deleteGoal')await act('goal:delete',{id:modal.goal.id});else if(modal.type==='deleteMemory'){await act('memory:delete',{id:modal.memory.id});setChat([]);}else await act('task:delete',{id:modal.task.id});setModal(null);setToast({text:'Removed from your workspace.'});}catch{}}}>Delete</button></div></Modal>}
  {state.blocks.length>0&&page==='Today'&&<button className="schedule-fab" onClick={()=>setModal('schedule')}><Clock3 size={15}/>Your plan<span>{state.blocks.filter(b=>localDate(new Date(b.start))===today).length} blocks</span></button>}
  {toast&&<div className={`toast ${toast.error?'error':''}`} role="status">{toast.error?<Flag size={16}/>:<CheckCircle2 size={16}/>}<span>{toast.text}</span>{toast.undo&&<button onClick={()=>{toast.undo();setToast(null);}}>Undo</button>}<IconButton label="Dismiss notification" onClick={()=>setToast(null)}><X size={14}/></IconButton></div>}
  </div>;
}
function PageTitle({eyebrow,title,description,action}){return <><div className="page-eyebrow">{eyebrow}</div><div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div>{action}</div></>;}
function Settings({state,act,setModal}){
  const settings=state.settings;
  const [provider,setProvider]=useState({aiMode:settings.aiMode,aiEndpoint:settings.aiEndpoint,aiModel:settings.aiModel,apiKey:'',transcriptionEndpoint:settings.transcriptionEndpoint});
  const [saving,setSaving]=useState(false);
  const toggle=async(key)=>{try{await act('settings:update',{[key]:!settings[key]});}catch{}};
  return <><PageTitle eyebrow="ON YOUR TERMS" title="Your space. Your choices." description="Choose what Argus remembers, and how it helps."/>
  <section className="settings-section"><div className="section-heading"><div><h2>Capture controls</h2><p>Everything starts off. You’re always in control.</p></div><button className="button small" onClick={()=>toggle('paused')}>{settings.paused?<Play size={14}/>:<Pause size={14}/>} {settings.paused?'Resume capture':'Pause all'}</button></div><div className="settings-card">{[{key:'activityEnabled',title:'App activity',description:'Foreground apps and time spent. No keystrokes.',icon:Monitor,status:state.runtime.activity},{key:'titlesEnabled',title:'Window titles',description:'Add the title of the active window to activity sessions.',icon:BookOpen},{key:'screenEnabled',title:'Screen context',description:'Read text from the foreground window every 60 seconds. Frames are processed in memory and discarded.',icon:Focus,status:state.runtime.screen},{key:'micEnabled',title:'Microphone',description:'Transcribe nearby speech using your local server. May include other people. Raw audio is discarded after each attempt.',icon:Mic,status:state.runtime.microphone},{key:'playbackEnabled',title:'Computer audio',description:'Transcribe what your computer plays. Includes calls and videos; task suggestions require review.',icon:Volume2,status:state.runtime.playback}].map(({key,title,description,icon:Icon,status})=><div className="setting-row" key={key}><span className="setting-icon"><Icon size={20}/></span><div><h3>{title}{status&&<span className="setting-status">{status}</span>}</h3><p>{description}</p></div><button className={`toggle ${settings[key]?'on':''}`} role="switch" aria-checked={settings[key]} aria-label={title} onClick={()=>toggle(key)}><span/></button></div>)}</div><p className="form-help">Screen and audio turn off when Argus restarts. Locking or suspending the computer pauses capture. Closing the window keeps Argus in the system tray; use Quit to stop it.</p></section>
  <section className="settings-section"><div className="section-heading"><div><h2>A little help thinking</h2><p>Offline planning works without an AI account.</p></div></div><form className="settings-card padded" onSubmit={async e=>{e.preventDefault();setSaving(true);try{const payload={...provider};if(!payload.apiKey)delete payload.apiKey;await act('settings:update',payload,'Provider settings saved.');}catch{}finally{setSaving(false);}}}><label>Assistant mode<select value={provider.aiMode} onChange={e=>setProvider({...provider,aiMode:e.target.value,aiEndpoint:e.target.value==='ollama'?'http://127.0.0.1:11434':e.target.value==='cloud'?'https://api.openai.com/v1':provider.aiEndpoint})}><option value="offline">Offline planner & keyword search</option><option value="ollama">Local model · Ollama</option><option value="cloud">Cloud model · OpenAI-compatible API</option></select></label>{provider.aiMode!=='offline'&&<><div className="form-grid"><label>Provider URL<input type="url" value={provider.aiEndpoint} onChange={e=>setProvider({...provider,aiEndpoint:e.target.value})} required/></label><label>Model name<input value={provider.aiModel} onChange={e=>setProvider({...provider,aiModel:e.target.value})} required/></label></div>{provider.aiMode==='cloud'&&<><div className="info-note"><ArrowUpRight size={17}/><p>Cloud mode sends your question, relevant memory excerpts, tasks, and goals to this provider. Saving this mode enables those requests when you ask Argus.</p></div><label>API key<input type="password" value={provider.apiKey} autoComplete="off" placeholder={settings.hasApiKey?'A key is stored securely. Enter to replace.':'Your provider API key'} onChange={e=>setProvider({...provider,apiKey:e.target.value})}/></label>{settings.hasApiKey&&<button type="button" className="text-link" onClick={()=>act('settings:update',{apiKey:''},'Stored API key removed.').catch(()=>{})}>Remove stored key</button>}</>}</>}<label>Local transcription server<input type="url" value={provider.transcriptionEndpoint} onChange={e=>setProvider({...provider,transcriptionEndpoint:e.target.value})} required/></label><p className="form-help">Use a running whisper.cpp-compatible HTTP server that accepts WAV uploads and returns JSON with a text field. Audio never goes to a remote transcription endpoint. Models are not bundled.</p><div className="form-end"><button className="button primary" disabled={saving}>{saving?'Saving…':'Save provider settings'}</button></div></form></section>
  <section className="settings-section"><div className="section-heading"><h2>Space for a realistic plan</h2></div><form className="settings-card padded" onSubmit={e=>{e.preventDefault();act('settings:update',Object.fromEntries(new FormData(e.currentTarget)),'Planning preferences saved.').catch(()=>{});}}><div className="form-grid"><label>Available focus minutes<input name="availableMinutes" type="number" min="15" max="720" defaultValue={settings.availableMinutes}/></label><label>My day ends at<input name="dayEnd" type="time" defaultValue={settings.dayEnd}/></label></div><div className="form-end"><button className="button">Save planning preferences</button></div></form></section>
  <section className="settings-section"><div className="section-heading"><h2>What stays out</h2><span className="tag tag-sage"><ShieldCheck size={12}/>Your boundaries</span></div><form className="settings-card padded" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);act('settings:update',{exclusions:data.get('exclusions').split('\n'),retentionDays:Number(data.get('retentionDays'))},'Privacy preferences saved.').catch(()=>{});}}><label>Excluded apps or window-title phrases<textarea name="exclusions" defaultValue={settings.exclusions.join('\n')} rows={4}/></label><p className="form-help">One phrase per line, matched without case sensitivity. Foreground matches pause all capture. Check the list when using sensitive apps. No automatic content filter can recognize every secret.</p><label>Keep captured history for (days)<input name="retentionDays" type="number" min="1" max="365" defaultValue={settings.retentionDays}/></label><p className="form-help">Shortening retention deletes older activity, memories, and their inbox suggestions. Accepted tasks and goals remain.</p><div className="form-end"><button className="button">Save privacy preferences</button></div></form></section>
  <section className="settings-section"><div className="section-heading"><h2>Your data belongs to you</h2></div><div className="settings-card padded"><div className="storage-message"><LockKeyhole size={21}/><div><h3>{preview?'Preview data only':'Encrypted on this Windows account'}</h3><p>{preview?'Sample data lives in this browser.':'Your database is stored in Local AppData, outside synced project folders. API keys are encrypted with it.'}</p></div></div>{state.runtime.error&&<p className="error-text" role="alert">{state.runtime.error}</p>}<div className="data-actions"><button className="button" onClick={()=>act('data:export',{},'Export completed.').catch(()=>{})}><Download size={15}/>Export readable JSON</button><button className="button" onClick={()=>setModal('deleteRecent')}>Delete last 15 minutes</button><button className="button danger-outline" onClick={()=>setModal('deleteAll')}><Trash2 size={15}/>Clear history</button></div><p className="form-help">Exports are readable files. Deleting local history cannot remove copies you exported or context already sent to a cloud provider.</p></div></section></>;
}
createRoot(document.getElementById('root')).render(<App/>);
